#!/bin/bash

cd ../input/

rm -rf upgrading/
rm -rf tutorial/
rm changelog.txt
rm coding-conventions.txt
rm contributing.txt
rm -rf changelogs/
rm installation.txt
rm installation-*
rm arraydata.txt
rm autocompletefield.txt
rm autocompletetextfield.txt
rm bbcode.txt
rm building-for-modularity.txt
rm built-in-page-controls.txt
rm cache-control.txt
rm casting.txt
rm checkboxfield.txt
rm checkboxsetfield.txt
rm cmsmain.txt
rm cmsmenu.txt
rm common-problems.txt
rm complextablefield.txt
rm compositefield.txt
rm configuration.txt
rm confirmedpasswordfield.txt
rm controller.txt
rm controllers.txt
rm creating-modules.txt
rm css.txt
rm csvbulkloader.txt
rm currencyfield.txt
rm customrequiredfields.txt
rm data-types.txt
rm database-abstraction.txt
rm database-structure.txt
rm database-troubleshooting.txt
rm datamodel.txt
rm dataobject.txt
rm dataobjectdecorator.txt
rm dataobjectset.txt
rm datefield.txt
rm datepickerfield.txt
rm db-build.txt
rm debugging.txt
rm deprecation.txt
rm director.txt
rm directory-structure.txt
rm documentation-guidelines.txt
rm dropdownfield.txt
rm email.txt
rm emailfield.txt
rm environment-management.txt
rm error-handling.txt
rm escape-types.txt
rm execution-pipeline.txt
rm fieldgroup.txt
rm filefield.txt
rm form-field-types.txt
rm form-validation.txt
rm form.txt
rm formaction.txt
rm formresponse.txt
rm functionaltest.txt
rm getcmsfields.txt
rm groupeddropdownfield.txt
rm hasmanycomplextablefield.txt
rm hasonecomplextablefield.txt
rm headerfield.txt
rm hiddenfield.txt
rm hierarchy.txt
rm how-page-security-works.txt
rm html.txt
rm htmleditorconfig.txt
rm htmleditorfield.txt
rm i18n.txt
rm image.txt
rm imagefield.txt
rm inlineformaction.txt
rm installing-modules.txt
rm javascript.txt
rm labelfield.txt
rm languagedropdownfield.txt
rm leftandmain.txt
rm listboxfield.txt
rm literalfield.txt
rm manifestbuilder.txt
rm manymanycomplextablefield.txt
rm mathspamprotection.txt
rm member.txt
rm member_groupset.txt
rm membertablefield.txt
rm migrationtask.txt
rm modeladmin.txt
rm module-maintainers.txt
rm module-releases.txt
rm modules.txt
rm multilingualcontent.txt
rm numericfield.txt
rm object.txt
rm objectmodel.txt
rm optionsetfield.txt
rm page-types.txt
rm page.txt
rm pagecomment.txt
rm pageless-controller.txt
rm partial-caching.txt
rm passwordfield.txt
rm permission.txt
rm postgres.txt
rm profiler.txt
rm publishing-to-web-server.txt
rm readonlyfield.txt
rm recovering_password.txt
rm requirements.txt
rm restfulserver.txt
rm restfulservice.txt
rm rssfeed.txt
rm rsyncmultihostpublisher.txt
rm sake.txt
rm scheduledtask.txt
rm searchcontext.txt
rm searchform.txt
rm secure-development.txt
rm security.txt
rm selectiongroup.txt
rm server-requirements.txt
rm sessions.txt
rm shortcodes.txt
rm simpleimagefield.txt
rm site-reports.txt
rm siteconfig.txt
rm sitetree.txt
rm soapmodelaccess.txt
rm sqlquery.txt
rm ssl.txt
rm start.txt
rm staticexporter.txt
rm staticpublisher.txt
rm tab.txt
rm tablefield.txt
rm tablelistfield.txt
rm tabset.txt
rm template-encoding.txt
rm templates.txt
rm testing-guide-glossary.txt
rm testing-guide-intro.txt
rm testing-guide-troubleshooting.txt
rm testing-guide.txt
rm redirectorpagetest.txt
rm releases.txt
rm silverstripe-on-mamp.txt
rm submitting-patches.txt 
rm subversion.txt
rm translation-offers.txt
rm translation.txt
rm -rf testing-howto/
rm textareafield.txt
rm textfield.txt
rm themes.txt
rm -rf themes/
rm translatable.txt
rm treedropdownfield.txt
rm treemultiselectfield.txt
rm tutorials.txt
rm typography.txt
rm uniquerestrictedtextfield.txt
rm upgrading.txt
rm urlvariabletools.txt
rm validator.txt
rm versioned.txt
rm virtualpage.txt
rm widgets.txt
rm recipes/adding-a-file-to-a-page.txt
rm recipes/adding-print-stylesheet.txt
rm recipes/dataobjectsearch.txt
rm recipes/populatedefaults.txt
rm recipes/list_by_month.txt
rm recipes/imageupload.txt
rm recipes/customising-content-in-your-templates.txt
rm windmill-testing.txt